In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import warnings
warnings.simplefilter('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [3]:
from tensorflow.keras.models import load_model
era_model = load_model("era_predictor_model_trained.h5")

In [4]:
df = pd.read_csv("prediction_data.csv")
df.head()

,Unnamed: 0,last_name,first_name,player_id,year,player_age,p_game,p_formatted_ip,p_total_pa,p_total_hits,...,straightaway_percent,opposite_percent,f_strike_percent,groundballs_percent,flyballs_percent,linedrives_percent,popups_percent,n_fastball_formatted,n_breaking_formatted,n_offspeed_formatted
0,40,Wainwright,Adam,425794,2021,40,32,206.1,828,168,...,37.1,22.9,64.3,48.7,21.5,25.4,4.4,59.7,33.8,6.4
1,41,Greinke,Zack,425844,2021,38,30,171.0,697,164,...,35.6,27.6,66.0,45.6,23.9,25.0,5.4,45.9,31.8,22.4
2,42,Morton,Charlie,450203,2021,38,33,185.2,756,136,...,34.4,27.3,58.2,49.5,20.0,25.2,5.4,58.0,36.7,5.3
3,43,Scherzer,Max,453286,2021,37,30,179.1,693,119,...,36.7,27.3,64.1,35.0,32.4,22.6,10.0,55.7,29.4,14.9
4,44,Miley,Wade,489119,2021,35,28,163.0,690,166,...,36.5,22.9,57.8,50.8,18.9,26.0,4.3,64.1,8.6,27.4

In [5]:
selected_features = df[['player_age',  'p_k_percent',\
                       'p_bb_percent', 'z_swing_percent', 'z_swing_miss_percent', 'oz_swing_percent', 'oz_swing_miss_percent',\
                        'oz_contact_percent', 'out_zone_percent', 'meatball_percent', 'iz_contact_percent', 'in_zone_percent',\
                        'edge_percent', 'whiff_percent', 'swing_percent', 'f_strike_percent', 'groundballs_percent', 'flyballs_percent', 'linedrives_percent',\
                        'popups_percent', 'n_fastball_formatted', 'n_breaking_formatted', 'n_offspeed_formatted' ]]

In [6]:
X = selected_features
y = df[['p_era']]
print(X.shape, y.shape)

(39, 23) (39, 1)

In [7]:
X_scaler = StandardScaler().fit(X)
X_scaled = X_scaler.transform(X)

In [9]:
prediction = era_model.predict(X_scaled)
prediction

array([[4.3023877],
       [4.0917845],
       [3.0415733],
       [3.0976064],
       [3.8945534],
       [3.4183927],
       [3.5257542],
       [4.24491  ],
       [2.1981792],
       [3.2166502],
       [2.0827157],
       [3.6764758],
       [4.4972873],
       [3.0437982],
       [2.0718362],
       [3.6911535],
       [4.517316 ],
       [2.7378602],
       [3.1773856],
       [2.970785 ],
       [2.5381522],
       [2.9094207],
       [2.0430038],
       [2.609764 ],
       [3.668193 ],
       [3.7304366],
       [5.0895224],
       [4.0814743],
       [2.2207298],
       [4.9460807],
       [3.96713  ],
       [3.55559  ],
       [4.4284315],
       [3.48829  ],
       [2.605124 ],
       [2.742186 ],
       [3.6308022],
       [4.2905574],
       [2.529336 ]], dtype=float32)

In [11]:
df["predicted_era"] = prediction
df.head()

,Unnamed: 0,last_name,first_name,player_id,year,player_age,p_game,p_formatted_ip,p_total_pa,p_total_hits,...,opposite_percent,f_strike_percent,groundballs_percent,flyballs_percent,linedrives_percent,popups_percent,n_fastball_formatted,n_breaking_formatted,n_offspeed_formatted,predicted_era
0,40,Wainwright,Adam,425794,2021,40,32,206.1,828,168,...,22.9,64.3,48.7,21.5,25.4,4.4,59.7,33.8,6.4,4.302388
1,41,Greinke,Zack,425844,2021,38,30,171.0,697,164,...,27.6,66.0,45.6,23.9,25.0,5.4,45.9,31.8,22.4,4.091784
2,42,Morton,Charlie,450203,2021,38,33,185.2,756,136,...,27.3,58.2,49.5,20.0,25.2,5.4,58.0,36.7,5.3,3.041573
3,43,Scherzer,Max,453286,2021,37,30,179.1,693,119,...,27.3,64.1,35.0,32.4,22.6,10.0,55.7,29.4,14.9,3.097606
4,44,Miley,Wade,489119,2021,35,28,163.0,690,166,...,22.9,57.8,50.8,18.9,26.0,4.3,64.1,8.6,27.4,3.894553

In [12]:
df.to_csv("pro_era_predictions_22.csv")